Repository fproldan/frappe, pull requests merged in 2022-05, with the labels that each got.

#133 Branding
  frappe/core/doctype/user/user.py
  frappe/email/doctype/email_account/test_mails/reply-4.raw
  frappe/email/queue.py
  frappe/public/js/frappe/ui/toolbar/about.js
  frappe/public/js/frappe/ui/toolbar/navbar.html
  frappe/tests/data/email_with_image.txt
  frappe/utils/install.py
  frappe/www/login.html
Labels: backport jphlions-staging

#129 Nuevos opciones para el campo "Tipo de dólar"
  frappe/geo/doctype/currency/currency.json
Labels: backport diamoerp-develop, backport diamoerp-staging, backport jphlions-staging

#141 feat: branding
  frappe/core/doctype/user/user.py
  frappe/email/doctype/email_account/test_mails/reply-4.raw
  frappe/email/queue.py
  frappe/public/js/frappe/ui/toolbar/about.js
  frappe/tests/data/email_with_image.txt
Labels: backport jphlions-staging

#144 Customize roles
  frappe/core/doctype/doctype/doctype.json
  frappe/custom/doctype/client_script/client_script.json
  frappe/custom/doctype/custom_field/custom_field.json
  frappe/custom/doctype/customize_form/customize_form.json
  frappe/event_streaming/doctype/document_type_mapping/document_type_mapping.json
  frappe/event_streaming/doctype/event_consumer/event_consumer.json
  frappe/event_streaming/doctype/event_producer/event_producer.json
  frappe/event_streaming/doctype/event_producer_last_update/event_producer_last_update.json
  frappe/event_streaming/doctype/event_sync_log/event_sync_log.json
  frappe/event_streaming/doctype/event_update_log/event_update_log.json
Labels: backport diamoerp-staging, backport jphlions-develop, backport jphlions-staging

#149 Traducción del botón Corregir
  frappe/public/js/frappe/form/toolbar.js
Labels: backport diamoerp-staging, backport jphlions-develop, backport jphlions-staging

#150 Modificiación script demo
  frappe/commands/create_demo.py
Labels: backport diamoerp-staging, backport jphlions-develop, backport jphlions-staging

#158 Traducciones
  frappe/public/js/frappe/form/footer/form_timeline.js
  frappe/public/js/frappe/form/sidebar/form_sidebar.js
  frappe/translations/es.csv
Labels: backport diamoerp-develop, backport jphlions-develop, backport jphlions-staging

#169 Maestros
  frappe/contacts/doctype/address/address.json
Labels: backport jphlions-staging

#176 feat(minor): Added app_name and app_logo in Website Settings
  frappe/translations/es.csv
  frappe/website/doctype/website_settings/website_settings.json
  frappe/www/login.html
  frappe/www/login.py
Labels: backport diamoerp-staging, backport jphlions-develop, backport jphlions-staging

#175 v13.13.0 (dev only)
  frappe/core/doctype/server_script/server_script.py
  frappe/core/doctype/server_script/test_server_script.py
  frappe/core/page/permission_manager/permission_manager.js
  frappe/public/js/frappe/form/form.js
  frappe/public/js/frappe/ui/filters/filter.js
  frappe/public/js/frappe/ui/page.js
  frappe/public/js/frappe/ui/tree.js
  frappe/public/js/frappe/utils/pretty_date.js
  frappe/public/js/frappe/views/treeview.js
  frappe/public/js/frappe/widgets/chart_widget.js
  frappe/query_builder/builder.py
  frappe/query_builder/utils.py
  frappe/utils/safe_exec.py
  requirements.txt
Labels: backport diamoerp-staging, backport jphlions-develop, backport jphlions-staging

#183 No se puede especificar Fecha de inicio al importar Suscripciones
  frappe/model/document.py
  frappe/public/js/frappe/ui/page.js
Labels: backport diamoerp-staging, backport jphlions-develop, backport jphlions-staging

#188 Excepción usuario Administrator
  frappe/auth.py
Labels: backport diamoerp-staging, backport jphlions-develop, backport jphlions-staging
