Repository fproldan/frappe, pull requests merged in 2022-08, with the labels that each got.

#225 Correcciones Módulo Proyecto
  frappe/utils/data.py
Labels: backport diamoerp-staging, backport jphlions-develop, backport jphlions-staging

#224 Ocultamiento de secciones / campos
  frappe/core/doctype/user/user.js
  frappe/core/doctype/user/user.json
Labels: backport jphlions-staging

#233 [Woocommerce] Informacion de Uso
  frappe/core/page/informacion_de_uso/informacion_de_uso.js
Labels: backport diamoerp-staging

#127 Tiendanube
  frappe/integrations/doctype/mercadopago_settings/mercadopago_settings.py
Labels: backport diamoerp-staging, backport jphlions-develop, backport jphlions-staging

#226 Bump to v13.14.1
  cypress/integration/control_link.js
  frappe/__init__.py
  frappe/client.py
  frappe/core/doctype/log_settings/log_settings.json
  frappe/core/doctype/server_script/test_server_script.py
  frappe/core/doctype/user/user.py
  frappe/custom/doctype/custom_field/custom_field.py
  frappe/custom/doctype/custom_field/test_custom_field.py
  frappe/database/database.py
  frappe/desk/form/utils.py
  frappe/desk/reportview.py
  frappe/email/doctype/auto_email_report/auto_email_report.py
  frappe/exceptions.py
  frappe/handler.py
  frappe/integrations/doctype/google_settings/google_settings.json
  frappe/integrations/doctype/google_settings/google_settings.py
  frappe/integrations/doctype/google_settings/test_google_settings.py
  frappe/model/db_query.py
  frappe/permissions.py
  frappe/public/icons/social/google_drive.svg
  frappe/public/js/frappe/file_uploader/FileUploader.vue
  frappe/public/js/frappe/form/controls/base_control.js
  frappe/public/js/frappe/form/controls/link.js
  frappe/public/js/frappe/form/controls/text_editor.js
  frappe/public/js/frappe/form/footer/footer.js
  frappe/public/js/frappe/form/footer/form_timeline.js
  frappe/public/js/frappe/form/form.js
  frappe/public/js/frappe/form/script_manager.js
  frappe/public/js/frappe/list/base_list.js
  frappe/public/js/frappe/request.js
  frappe/public/js/frappe/utils/utils.js
  frappe/public/js/frappe/web_form/web_form.js
  frappe/public/js/integrations/google_drive_picker.js
  frappe/rate_limiter.py
  frappe/tests/test_permissions.py
  frappe/utils/data.py
  frappe/utils/response.py
  frappe/utils/safe_exec.py
  frappe/website/doctype/web_form/test_web_form.py
  frappe/website/doctype/web_form/web_form.py
  frappe/website/doctype/website_theme/website_theme.js
Labels: backport diamoerp-staging, backport jphlions-develop, backport jphlions-staging

#241 HR DOMAIN
  frappe/desk/doctype/dashboard_chart/dashboard_chart.py
  frappe/translations/es.csv
Labels: backport diamoerp-staging, backport jphlions-develop, backport jphlions-staging

#247 Modificaciones en las configuraciones del Sistema
  frappe/core/doctype/system_settings/system_settings.json
  frappe/core/workspace/settings/settings.json
Labels: backport diamoerp-staging, backport jphlions-develop, backport jphlions-staging

#251 Eliminacion de mensaje de repeticion automatica
  frappe/automation/doctype/auto_repeat/auto_repeat.js
Labels: backport diamoerp-staging, backport jphlions-develop, backport jphlions-staging
