Repository fproldan/frappe, pull requests merged in 2022-03, with the labels that each got.

#76 [HOTFIX] Customize is not listed in menu item [Print]
  frappe/printing/page/print/print.js
Labels: backport diamoerp-develop, backport diamoerp-staging, backport jphlions-develop, backport jphlions-staging

#75 Error adhesion pagos360
  frappe/integrations/doctype/pagos360_settings/pagos360_settings.py
Labels: backport diamoerp-staging, backport jphlions-develop, backport jphlions-staging

#74 Asignar nombre luego de validar
  frappe/core/doctype/doctype/doctype.json
  frappe/database/schema.py
  frappe/desk/form/save.py
  frappe/model/document.py
  frappe/model/naming.py
  frappe/model/rename_doc.py
  frappe/public/js/frappe/form/save.js
  frappe/translations/es.csv
Labels: backport diamoerp-staging, backport jphlions-develop, backport jphlions-staging

#62 Translations
  frappe/translations/es.csv
Labels: backport diamoerp-staging, backport jphlions-develop, backport jphlions-staging

#73 Actualizar jinja
  requirements.txt
Labels: backport diamoerp-staging, backport jphlions-develop, backport jphlions-staging

#72 Obtener el precio del dolar diariamente
  frappe/geo/doctype/currency/currency.json
Labels: backport diamoerp-develop, backport diamoerp-staging, backport jphlions-staging

#100 Corrección Formato por defecto Factura de Venta
  frappe/printing/doctype/print_format/print_format.js
Labels: backport diamoerp-staging, backport jphlions-develop, backport jphlions-staging
